name: Setup Frontend
description: Setup Frontend

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@5cb1df66ed5e1fb3c670ea0b62fd17a76979826a # v2.3.1

    - name: Get bun cache directory
      id: cache-dir
      shell: bash
      run: echo "dir=$(bun pm cache)" >> "${GITHUB_OUTPUT}"
      working-directory: frontend

    - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ steps.cache-dir.outputs.dir }}
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - run: bun install --frozen-lockfile
      working-directory: frontend
      shell: bash
