version: "1.1"
name: Test Badges
config:
  http:
    baseURL: https://badgen.org
env:
  zennUsername: kou_pg_0131
  qiitaUsername: koki_develop
  atcoderUsername: chokudai
  blueskyUsername: koki.me
tests:
  app:
    steps:
      - name: Home
        http:
          url: /
          method: GET
          check:
            status: 200
            headers:
              content-type: text/html; charset=utf-8
      - name: Privacy Policy
        http:
          url: /privacy
          method: GET
          check:
            status: 200
            headers:
              content-type: text/html; charset=utf-8

  zenn:
    steps:
      - name: Zenn - Likes
        http:
          url: /img/zenn/${{env.zennUsername}}/likes
          method: GET
          check:
            status: 200
            headers:
              content-type: image/svg+xml
      - name: Zenn - Followers
        http:
          url: /img/zenn/${{env.zennUsername}}/followers
          method: GET
          check:
            status: 200
            headers:
              content-type: image/svg+xml
      - name: Zenn - Articles
        http:
          url: /img/zenn/${{env.zennUsername}}/articles
          method: GET
          check:
            status: 200
            headers:
              content-type: image/svg+xml
      - name: Zenn - Books
        http:
          url: /img/zenn/${{env.zennUsername}}/books
          method: GET
          check:
            status: 200
            headers:
              content-type: image/svg+xml
      - name: Zenn - Scraps
        http:
          url: /img/zenn/${{env.zennUsername}}/scraps
          method: GET
          check:
            status: 200
            headers:
              content-type: image/svg+xml

  qiita:
    steps:
      - name: Qiita - Contributions
        http:
          url: /img/qiita/${{env.qiitaUsername}}/contributions
          method: GET
          check:
            status: 200
            headers:
              content-type: image/svg+xml
      - name: Qiita - Followers
        http:
          url: /img/qiita/${{env.qiitaUsername}}/followers
          method: GET
          check:
            status: 200
            headers:
              content-type: image/svg+xml
      - name: Qiita - Articles
        http:
          url: /img/qiita/${{env.qiitaUsername}}/articles
          method: GET
          check:
            status: 200
            headers:
              content-type: image/svg+xml

  atcoder:
    steps:
      - name: AtCoder - Rating
        http:
          url: /img/atcoder/${{env.atcoderUsername}}/rating/algorithm
          method: GET
          check:
            status: 200
            headers:
              content-type: image/svg+xml
      - name: AtCoder - Rating(Heuristic)
        http:
          url: /img/atcoder/${{env.atcoderUsername}}/rating/heuristic
          method: GET
          check:
            status: 200
            headers:
              content-type: image/svg+xml

  bluesky:
    steps:
      - name: Bluesky - Followers
        http:
          url: /img/bluesky/${{env.blueskyUsername}}/followers
          method: GET
          check:
            status: 200
            headers:
              content-type: image/svg+xml
      - name: Bluesky - Posts
        http:
          url: /img/bluesky/${{env.blueskyUsername}}/posts
          method: GET
          check:
            status: 200
            headers:
              content-type: image/svg+xml
