version: "1.0"
name: Test Badges
config:
  baseURL: https://badgen.org
env:
  zennUsername: kou_pg_0131
  qiitaUsername: koki_develop
  atcoderUsername: chokudai
tests:
  zenn:
    steps:
      - name: Zenn - Likes
        url: /img/zenn/{{env.zennUsername}}/likes
        method: GET
        check:
          status: 200
      - name: Zenn - Followers
        url: /img/zenn/{{env.zennUsername}}/followers
        method: GET
        check:
          status: 200
      - name: Zenn - Articles
        url: /img/zenn/{{env.zennUsername}}/articles
        method: GET
        check:
          status: 200
      - name: Zenn - Books
        url: /img/zenn/{{env.zennUsername}}/books
        method: GET
        check:
          status: 200
      - name: Zenn - Scraps
        url: /img/zenn/{{env.zennUsername}}/scraps
        method: GET
        check:
          status: 200

  qiita:
    steps:
      - name: Qiita - Contributions
        url: /img/qiita/{{env.qiitaUsername}}/contributions
        method: GET
        check:
          status: 200
      - name: Qiita - Followers
        url: /img/qiita/{{env.qiitaUsername}}/followers
        method: GET
        check:
          status: 200
      - name: Qiita - Articles
        url: /img/qiita/{{env.qiitaUsername}}/articles
        method: GET
        check:
          status: 200

  atcoder:
    steps:
      - name: AtCoder - Rating
        url: /img/atcoder/{{env.atcoderUsername}}/rating/algorithm
        method: GET
        check:
          status: 200
      - name: AtCoder - Rating(Heuristic)
        url: /img/atcoder/{{env.atcoderUsername}}/rating/heuristic
        method: GET
        check:
          status: 200
