# TODO: vitest 経由で実行するようにしたい
#       参考: https://github.com/stepci/stepci/blob/main/docs/using-test-tools.md
version: "1.0"
name: Test Badges
config:
  baseURL: https://badgen.org
env:
  zennUsername: kou_pg_0131
  qiitaUsername: koki_develop
  atcoderUsername: chokudai
tests:
  app:
    steps:
      - name: Home
        url: /
        method: GET
        check:
          status: 200
          headers:
            content-type: text/html; charset=utf-8
      - name: Privacy Policy
        url: /privacy
        method: GET
        check:
          status: 200
          headers:
            content-type: text/html; charset=utf-8

  zenn:
    steps:
      - name: Zenn - Likes
        url: /img/zenn/{{env.zennUsername}}/likes
        method: GET
        check:
          status: 200
          headers:
            content-type: image/svg+xml
      - name: Zenn - Followers
        url: /img/zenn/{{env.zennUsername}}/followers
        method: GET
        check:
          status: 200
          headers:
            content-type: image/svg+xml
      - name: Zenn - Articles
        url: /img/zenn/{{env.zennUsername}}/articles
        method: GET
        check:
          status: 200
          headers:
            content-type: image/svg+xml
      - name: Zenn - Books
        url: /img/zenn/{{env.zennUsername}}/books
        method: GET
        check:
          status: 200
          headers:
            content-type: image/svg+xml
      - name: Zenn - Scraps
        url: /img/zenn/{{env.zennUsername}}/scraps
        method: GET
        check:
          status: 200
          headers:
            content-type: image/svg+xml

  qiita:
    steps:
      - name: Qiita - Contributions
        url: /img/qiita/{{env.qiitaUsername}}/contributions
        method: GET
        check:
          status: 200
          headers:
            content-type: image/svg+xml
      - name: Qiita - Followers
        url: /img/qiita/{{env.qiitaUsername}}/followers
        method: GET
        check:
          status: 200
          headers:
            content-type: image/svg+xml
      - name: Qiita - Articles
        url: /img/qiita/{{env.qiitaUsername}}/articles
        method: GET
        check:
          status: 200
          headers:
            content-type: image/svg+xml

  atcoder:
    steps:
      - name: AtCoder - Rating
        url: /img/atcoder/{{env.atcoderUsername}}/rating/algorithm
        method: GET
        check:
          status: 200
          headers:
            content-type: image/svg+xml
      - name: AtCoder - Rating(Heuristic)
        url: /img/atcoder/{{env.atcoderUsername}}/rating/heuristic
        method: GET
        check:
          status: 200
          headers:
            content-type: image/svg+xml
