name: e2e

on:
  workflow_call:

jobs:
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: setup node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version-file: "frontend/package.json"
          cache: yarn
          cache-dependency-path: frontend/yarn.lock
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: e2e
        env:
          STEPCI_DISABLE_ANALYTICS: "1"
        run: yarn e2e
