name: CI

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    permissions:
      contents: read
    uses: ./.github/workflows/_ci.yml
